### ISSUE TITLE
[PE-D] Unable to view the last client

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T12-1/tp#275]
unable to view index 10 if index 10 is the last client

![image.png](https://raw.githubusercontent.com/bingcheng45/ped/main/files/d90d5b8e-5c6a-4f34-ad7d-e7ef923ef30c.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: bingcheng45/ped#9

**Comment by SkyBlaise99** [comment]
Unable to replicate the issue
